---
title: "homework3 report"
author: "王梓"
date: "2024-07-02"
output: html_document
---

```{r}
if (!require(ggplot2)) install.packages("ggplot2")
library(ggplot2)

gmp <- read.table("data/gmp.dat")
gmp$pop <- round(gmp$gmp/gmp$pcgmp)
```

## 1.
```{r}
func <- function(x, y0, a) {
  return(y0 * x ^ a)
}
ggplot(data = gmp) + 
  geom_point(aes(x = pop, y = pcgmp)) + 
  geom_line(aes(x = pop, y = func(pop, 6493.2563726, 0.1276921)), col = "blue") +
  geom_line(aes(x = pop, y = func(pop, 6493.2563726, 0.1)), col = "red") +
  geom_line(aes(x = pop, y = func(pop, 6493.2563726, 0.15)), col = "green")
```

## 2.
```{r}
mse <- function(para, N = gmp$pop, Y = gmp$pcgmp) {
  return(mean((Y - para[1] * N ^ para[2]) ^ 2))
}
```
```{r}
mse(c(6611,0.15))
mse(c(5000,0.10))
```
## 3.
```{r}
nlm(mse, c(y0=6611,a=1/8))
```
```{r}
nlm(mse, c(y0=6000,a=0.1))
```
```{r}
nlm(mse, c(y0=6500,a=0.15))
```
minimum 表示其找到的函数最小值，estimate 表示找到 minimum 值时对应的变量数值。

## 4.
```{r}
plm <- function(y0, a, N = gmp$pop, Y = gmp$pcgmp) {
  result <- nlm(mse, c(y0 = y0, a = a))
  return(list(y0 = result$estimate[1], 
              a = result$estimate[2], 
              MSE = result$minimum))
}
```

```{r}
plm(y0 = 6611, a = 0.15)
```

```{r}
plm(y0 = 5000, a = 0.1)
```

plm 中调用的 nlm 函数使用的是牛顿型算法来寻找最小值，其结果会与初始值的选取有关。
此处当初始值选为 (y0 = 6611, a = 0.15) 时会得到更小的 MSE。

## 5.
### a.
```{r}
mean(gmp$pcgmp)
sd(gmp$pcgmp)

(sum((gmp$pcgmp - mean(gmp$pcgmp)) ^ 2) / (length(gmp$pcgmp) - 1)) ^ 0.5
```
### b.
```{r}
mean_pcgmp_except <- function(i) {
  return(mean(gmp$pcgmp[-i]))
}
```

```{r}
mean_pcgmp_except(i = 2)
```
### c.
```{r}
jackknifed.means <- c()
for (i in 1:length(gmp$pcgmp)) 
  jackknifed.means <- c(jackknifed.means, mean_pcgmp_except(i))
```

### d.
```{r}
jackknife.variance <- (length(gmp$pcgmp) - 1) * 
  mean((jackknifed.means - mean(jackknifed.means)) ^ 2)
(jackknife.sd <- jackknife.variance ^ 0.5)
```
## 6
```{r}
plm.jackknife <- function(y0, a, N = gmp$pop, Y = gmp$pcgmp) {
  jackknife.estimates <- list(y0 = c(), a = c())
  for (i in 1:length(N)) {
    estimates <- plm(y0, a, N[-i], Y[-i])
    jackknife.estimates$y0 <- c(jackknife.estimates$y0, estimates$y0)
    jackknife.estimates$a <- c(jackknife.estimates$a, estimates$a)
  }
  means <- lapply(jackknife.estimates, mean)
  y0.variance = (length(N) - 1) * mean((jackknife.estimates$y0 - means$y0) ^ 2)
  a.variance = (length(N) - 1) * mean((jackknife.estimates$a - means$a) ^ 2)
  return(list(y0.sd = y0.variance ^ 0.5, a.sd = a.variance ^ 0.5))
}
```

```{r}
options(warn = -1)
plm.jackknife(y0 = 6611,a = 1/8)
# y0 = 5000
# a = 0.1
# N = gmp$pop
# Y = gmp$pcgmp
#   jackknife.estimates <- list(y0 = c(), a = c())
#   for (i in 1:length(N)) {
#     estimates <- plm(y0, a, N[-i], Y[-i])
#     jackknife.estimates$y0 <- c(jackknife.estimates$y0, estimates$y0)
#     jackknife.estimates$a <- c(jackknife.estimates$a, estimates$a)
#   }
#   means <- lapply(jackknife.estimates, mean)
#   y0.variance = (length(N) - 1) * mean((jackknife.estimates$y0 - means$y0) ^ 2)
#   a.variance = (length(N) - 1) * mean((jackknife.estimates$a - means$a) ^ 2)
#   (list(y0.sd = y0.variance ^ 0.5, a.sd = a.variance ^ 0.5))
```
## 7.
```{r}
gmp2013 <- read.table('data/gmp-2013.dat', header = T)
gmp2013$pop <- gmp2013$gmp / gmp2013$pcgmp
```

```{r}
options(warn = -1)
plm(y0 = 661, a= 1/8, N = gmp2013$pop, Y = gmp2013$pcgmp)
plm.jackknife(y0 = 6611, a = 1/8, N = gmp2013$pop, Y = gmp2013$pcgmp)
```

